repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        additional_dependencies: ['types-setuptools', 'types-requests']

-   repo: local
    hooks:
    -   id: python-tests
        name: Run Python Tests
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-push]  # Run only on push, not on every commit
