version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # Add poetry installation
    python_requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

formats:
  - pdf
  - epub
