[tool.poetry]
name = "chronowords"
version = "0.1.0"
description = ""
authors = ["Zoltan Varju <zoltan.varju@crowintelligence.org>"]
readme = "README.md"
packages = [{include = "chronowords", from = "src"}]

[tool.poetry.build]
script = "setup.py"
generate-setup-file = false

[tool.poetry.dependencies]
python = "3.12"
numpy = "^1.26.0"
scipy = "^1.12.0"
cython = "^3.0.11"
setuptools = "^75.8.0"
mmh3 = "^5.0.1"
nltk = "^3.9.1"
scikit-learn = "^1.6.1"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
pytest = "^8.3.4"
isort = "^5.13.2"
requests = "^2.32.3"
spacy = "^3.8.4"
pandas = "^2.2.3"
notebook = "^7.3.2"
altair = "^5.5.0"

[build-system]
requires = ["poetry-core", "setuptools", "wheel", "Cython", "numpy"]
build-backend = "poetry.core.masonry.api"