[tool.poetry]
name = "chronowords"
version = "0.1.0"
description = ""
authors = ["Zoltan Varju <zoltan.varju@crowintelligence.org>"]
readme = "README.md"
packages = [{include = "chronowords", from = "src"}]

[tool.poetry.build]
script = "setup.py"
generate-setup-file = false

[tool.poetry.dependencies]
python = "3.12"
scipy = "^1.15.1"
cython = "^3.0.11"
datasketch = "^1.6.5"
setuptools = "^75.8.0"


[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
pytest = "^8.3.4"
isort = "^5.13.2"
requests = "^2.32.3"
spacy = "^3.8.4"

[build-system]
requires = ["poetry-core",  "setuptools", "wheel", "Cython", "numpy"]
build-backend = "poetry.core.masonry.api"
